
import './globals.css'
//nextjs feature for importing fonts without loading them in html
import { Rubik } from 'next/font/google'

//components
import Navbar from './components/navbar'
const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    //html and body tags are edfined here, not in every page
    <html lang="en">
      <body className={rubik.className}>
        <navbar />
        {children}
        </body>
    </html>
  )
}
